branches:
  only:
   - master
language: r
r:
- release

cache:
  packages: yes
  directories:
    - $HOME/bin

before_install:
    r_packages:
        - bookdown

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

install:
- npm install -g firebase-tools

after_success:
 - firebase deploy --only hosting --token "$FIREBASE_TOKEN"